apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
{{- with .Values.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- with .Values.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
