apiVersion: v2
name: bar-assistant
description: Bar Assistant - self-hosted cocktail recipe manager
type: application
version: 0.1.6
appVersion: "5.11.2"

dependencies:
  - name: meilisearch
    version: "0.19.0"
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
