apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actual.fullname" . }}
  labels:
    {{- include "actual.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "actual.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "actual.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "actual.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ACTUAL_PORT
              value: {{ .Values.service.port | quote }}
            - name: ACTUAL_DATA_DIR
              value: {{ .Values.files.dataDirectory | quote }}
            - name: ACTUAL_SERVER_FILES
              value: {{ .Values.files.server | quote }}
            - name: ACTUAL_USER_FILES
              value: {{ .Values.files.user | quote }}
            - name: ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB
              value: {{ .Values.upload.fileSizeSyncLimitMB | quote }}
            - name: ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB
              value: {{ .Values.upload.syncEncryptedFileSizeLimitMB | quote }}
            - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
              value: {{ .Values.upload.fileSizeLimitMB | quote }}
            - name: ACTUAL_LOGIN_METHOD
              value: {{ .Values.login.method | quote }}
            {{- if .Values.login.skipSSLVerification }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- end }}
            {{- if .Values.login.openid.enabled }}
            {{- $secretName := .Values.login.openid.existingSecret | default (printf "%s-openid" (include "actual.fullname" .)) }}
            {{- if or .Values.login.openid.existingSecret (and .Values.login.openid.clientId .Values.login.openid.clientSecret) }}
            - name: ACTUAL_OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.login.openid.clientIdKey }}
            - name: ACTUAL_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.login.openid.clientSecretKey }}
            {{- end }}
            {{- if .Values.login.openid.discoveryUrl }}
            - name: ACTUAL_OPENID_DISCOVERY_URL
              value: {{ .Values.login.openid.discoveryUrl | quote }}
            {{- end }}
            {{- if .Values.login.openid.authorizationEndpoint }}
            - name: ACTUAL_OPENID_AUTHORIZATION_ENDPOINT
              value: {{ .Values.login.openid.authorizationEndpoint | quote }}
            {{- end }}
            {{- if .Values.login.openid.tokenEndpoint }}
            - name: ACTUAL_OPENID_TOKEN_ENDPOINT
              value: {{ .Values.login.openid.tokenEndpoint | quote }}
            {{- end }}
            {{- if .Values.login.openid.userInfoEndpoint }}
            - name: ACTUAL_OPENID_USERINFO_ENDPOINT
              value: {{ .Values.login.openid.userInfoEndpoint | quote }}
            {{- end }}
            {{- if .Values.login.openid.authMethod }}
            - name: ACTUAL_OPENID_AUTH_METHOD
              value: {{ .Values.login.openid.authMethod | quote }}
            {{- end }}
            {{- if .Values.login.openid.enforce }}
            - name: ACTUAL_OPENID_ENFORCE
              value: "true"
            {{- end }}
            {{- if .Values.login.openid.serverHostname }}
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: {{ .Values.login.openid.serverHostname | quote }}
            {{- else if .Values.ingress.enabled }}
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: "https://{{ (index .Values.ingress.hosts 0).host }}/"
            {{- end }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.files.dataDirectory }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "actual.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
