{{- if and (eq .Values.login.method "openid") .Values.login.openid.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actual.fullname" . }}-openid
  labels:
    {{- include "actual.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.login.openid.clientSecret | b64enc }}
{{- end }}