{{- if and .Values.login.openid.enabled (not .Values.login.openid.existingSecret) }}
{{- if and .Values.login.openid.clientId .Values.login.openid.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actual.fullname" . }}-openid
  labels:
    {{- include "actual.labels" . | nindent 4 }}
type: Opaque
stringData:
  client_id: {{ .Values.login.openid.clientId | quote }}
  client_secret: {{ .Values.login.openid.clientSecret | quote }}
{{- end }}
{{- end }}
