apiVersion: v1
kind: Service
metadata:
  name: {{ include "bar-assistant.fullname" . }}-api
  labels:
    {{- include "bar-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bar-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
{{- if .Values.saltRim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bar-assistant.fullname" . }}-saltrim
  labels:
    {{- include "bar-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: saltrim
spec:
  type: {{ .Values.saltRim.service.type }}
  ports:
    - port: {{ .Values.saltRim.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bar-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: saltrim
{{- end }}
